#pragma once

#include <span>
#include <vector>

namespace Rtx
{
    /// A square tile of blue noise: `RANDOM_STREAMS` independent masks over the same pixels. Blue
    /// noise does not make a sample better, it pushes the error into the high frequencies, which
    /// a filter takes out cleanly where a hash's white error leaves blotches no filter can tell
    /// from smooth lighting. Generated by void-and-cluster rather than shipped as a mask, so a
    /// test can check that the ranks are a permutation and the spectrum has no low frequencies.
    class BlueNoise
    {
    public:
        /// The one tile, built on first use: a tenth of a second, paid once and not per pipeline.
        static const BlueNoise& shared();

        BlueNoise(const BlueNoise&) = delete;
        BlueNoise& operator=(const BlueNoise&) = delete;

        /// Values in `[0, 1)`, one pixel's `RANDOM_STREAMS` channels at a time, row by row.
        /// Interleaved rather than planar, so that the channels one pixel reads sit in one cache
        /// line: a shader that draws a pair touches two of them and never the same channel twice.
        std::span<const float> getValues() const { return mValues; }

    private:
        BlueNoise();

        std::vector<float> mValues;
    };
}
